INFO:__main__:PEX 03 start.
INFO:__main__:Connecting to device...
INFO:autopilot:ArduCopter V4.1.0-dev (428c9ef0)
INFO:autopilot:a3d9197b765643568af09eb2bd3e5ce7
INFO:autopilot:Frame: QUAD
INFO:__main__:Device connected.
INFO:root:Device version: APM:Copter-None.None.NoneUnknownReleaseType, log=
INFO:__main__:Looking for mission to execute...
INFO:__main__:Arming device...
INFO:__main__:Device armed: True.
INFO:__main__:Device takeoff...
INFO:__main__:Current altitude: 20.005
INFO:__main__:Changing device mode from VehicleMode:GUIDED to AUTO...
INFO:autopilot:Mission: 3 WP
INFO:__main__:Device mode = VehicleMode:AUTO.
INFO:__main__:backing up old images...
INFO:root:Searching for target...
INFO:root:Changing device mode from VehicleMode:AUTO to GUIDED...
INFO:root:Device mode = VehicleMode:GUIDED.
INFO:__main__:Goto point: 21.3210579, -157.9241353, 1, 20.004...
INFO:__main__:Current altitude: 20.008
INFO:__main__:Current lat: 21.3210615
INFO:root:Current lon: (-157.9241448, <Logger __main__ (DEBUG)>)
INFO:__main__:Relative position to destination: 1.0001999600079983,1.0000001688471565, 1.0000000601554664
INFO:__main__:Program exception: ['Traceback (most recent call last):\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 744, in <module>\n    conduct_mission()\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 657, in conduct_mission\n    determine_drone_actions((last_lat, last_lon), frm_display, target_sightings, x, y, radius)\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 686, in determine_drone_actions\n    new_lat, new_lon = get_new_lat_lon(last_obj_lat, last_obj_lon, last_obj_heading, distance)\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 142, in get_new_lat_lon\n    heading = math.radians(last_obj_heading)\n', 'TypeError: must be real number, not NoneType\n']
