INFO:__main__:PEX 03 start.
INFO:__main__:Connecting to device...
INFO:autopilot:ArduCopter V4.1.0-dev (428c9ef0)
INFO:autopilot:a3d9197b765643568af09eb2bd3e5ce7
INFO:autopilot:Frame: QUAD
INFO:__main__:Device connected.
INFO:root:Device version: APM:Copter-None.None.NoneUnknownReleaseType, log=
INFO:__main__:Looking for mission to execute...
INFO:__main__:Arming device...
INFO:__main__:Device armed: True.
INFO:__main__:Device takeoff...
INFO:__main__:Current altitude: 24.366
INFO:__main__:Changing device mode from VehicleMode:GUIDED to AUTO...
INFO:autopilot:Mission: 4 RTL
INFO:__main__:Device mode = VehicleMode:AUTO.
INFO:__main__:backing up old images...
INFO:root:Searching for target...
INFO:root:Changing device mode from VehicleMode:AUTO to GUIDED...
INFO:root:Device mode = VehicleMode:GUIDED.
INFO:__main__:Goto point: 21.3213627, -157.9242715, 1, 24.362...
INFO:__main__:Current altitude: 24.364
INFO:__main__:Current lat: 21.3213725
INFO:root:Current lon: (-157.9242674, <Logger __main__ (DEBUG)>)
INFO:__main__:Relative position to destination: 1.0000820950660867,1.0000004596329106, 0.9999999740381895
INFO:__main__:Program exception: ['Traceback (most recent call last):\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 678, in <module>\n    conduct_mission()\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 512, in conduct_mission\n    if (bbox[0] + int(bbox[2]/2)) < (frame_w / 2):\n', "NameError: name 'frame_w' is not defined\n"]
